language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database cake_test_db;' -U postgres

env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true
  include:
    - php: 5.4

install:
  - composer self-update
  - composer install --dev

before_script:
  - cp phpunit.xml.dist phpunit.xml

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then phpunit --stderr; fi"

notifications:
  email: false
